"""empty message

Revision ID: 3dd6c07117c7
Revises: 0af0a05f847f
Create Date: 2023-04-05 07:55:26.590110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd6c07117c7'
down_revision = '0af0a05f847f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
